# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- None

pool:
  name: LAptop

stages:

- stage: Compile
  displayName: 'Maven Compile Stage'
  jobs:
  - job: CompileJob
    steps:
    - script: mvn clean compile
      displayName: 'Run mvn compile'

- stage: Test
  displayName: 'Maven Test Stage'
  dependsOn: Compile
  jobs:
  - job: TestJob
    steps:
    - script: mvn test
      displayName: 'Run mvn test'
    



- stage: Sonar
  displayName: 'sonar_scan'
  dependsOn: Test
  jobs:
  - job: sonar
    steps:
    - task: SonarQubePrepare@8
      inputs:
        SonarQube: 'sonar-svc'
        scannerMode: 'other'
        projectKey: 'Testing'
        projectName: 'Testing'
    - script: mvn verify sonar:sonar


- stage: Cleanup
  displayName: 'Final Cleanup'
  condition: always()
  jobs:
  - job: CleanupJob
    steps:
    - script: |
        echo "Cleaning workspace: $(Pipeline.Workspace)"
        rm -rf $(Pipeline.Workspace)/*





     